<?php

namespace Database\Seeders;

use App\Models\Carrusel;
use App\Models\Ciudad;
use App\Models\Especialidad;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder{
    public function run(): void{
        Carrusel::create(["src"=>"1.png"]);
        Carrusel::create(["src"=>"2.png"]);
        Carrusel::create(["src"=>"3.png"]);

        Especialidad::create(["img"=>"10.png", "nombre"=>"Dentista"]); //1
        Especialidad::create(["img"=>"11.png", "nombre"=>"Cardiologo"]); //2
        Especialidad::create(["img"=>"12.png", "nombre"=>"Dermatologo"]); //3
        Especialidad::create(["img"=>"13.png", "nombre"=>"Ayurveda"]); //4
        Especialidad::create(["img"=>"14.png", "nombre"=>"Oftalmologo"]); //5
        Especialidad::create(["img"=>"15.png", "nombre"=>"Ortopedista"]); //6
        Especialidad::create(["img"=>"16.png", "nombre"=>"Urologo"]); //7
        Especialidad::create(["img"=>"17.png", "nombre"=>"Ginecologo"]); //8
        Especialidad::create(["img"=>"18.png", "nombre"=>"Gastroenterologo"]); //9
        Especialidad::create(["img"=>"19.png", "nombre"=>"Homeopata"]); //10
        Especialidad::create(["img"=>"20.png", "nombre"=>"Neumologo"]); //11
        Especialidad::create(["img"=>"21.png", "nombre"=>"Cuidado de la piel"]); //12

        Ciudad::create(["nombre"=>"San Jose"]); //1
        Ciudad::create(["nombre"=>"Dallas"]); //2
        Ciudad::create(["nombre"=>"San Antonio"]); //3
        Ciudad::create(["nombre"=>"Philadelphia"]); //4
        Ciudad::create(["nombre"=>"Phoenix"]); //5
        Ciudad::create(["nombre"=>"Houston"]); //6
        Ciudad::create(["nombre"=>"Los Angeles"]); //7
        Ciudad::create(["nombre"=>"Chicago"]); //8
        Ciudad::create(["nombre"=>"Washington"]); //9
        Ciudad::create(["nombre"=>"New York"]); //10


//        protected $fillable = [
////            'name',
////            'email',
////            'password',
////            'especialidad_id',
////            'ciudad_id',
////            'celular',
////            'avatar',
////            'horas_de_trabajo',
////            'tarifa',
////            'acerca',
////            'servicio',
////            'cuidado',
////            'direccion',
////            'lat',
////            'lng',
////            'status', // active, inactive, banned
////            'role', // user, admin, doctor, etc.
////        ];
///  [
//{
//id: 12,
//name: "Dr Joseph Martina",
//email: "martina@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "8:00 AM to 6:00 PM",
//address: "200 Murray Street, New York, NY 10282, USA",
//lat: "40.704707531153424",
//lon: "-74.0118092868164",
//phoneno: "2012568563",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/17.jpg",
//department_id: 9,
//password: "123456",
//created_at: "2023-08-01T05:20:27.000000Z",
//updated_at: "2023-08-01T05:20:27.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "1695299124#2",
//connectycube_user_id: "12576475",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 5,
//phone: "2012568563",
//service: "Gastroenterology",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/12" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/12" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/12')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 11,
//name: "Dr Catholina Marin",
//email: "Catholina@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "9:00 AM to 6:00 PM",
//address: "70 Broad St, New York, NY 10004, USA",
//lat: "40.7524492855458",
//lon: "-74.00511449311523",
//phoneno: "023560593",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/14.jpg",
//department_id: 8,
//password: "123456",
//created_at: "2023-08-01T05:19:51.000000Z",
//updated_at: "2023-08-01T05:19:51.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "852448890#2",
//connectycube_user_id: "12576474",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 4,
//phone: "023560593",
//service: "Gynecologist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/11" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/11" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/11')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 10,
//name: "Dr Andrew Simons",
//email: "Simonse@gmil.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "10:0 AM to 8:00 PM",
//address: "281 11th Ave, New York, NY 10001, USA",
//lat: "40.711343992980424",
//lon: "-73.98623174165044",
//phoneno: "230203203",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/15.jpg",
//department_id: 6,
//password: "123456",
//created_at: "2023-08-01T05:19:26.000000Z",
//updated_at: "2023-08-01T05:19:26.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "51130679#2",
//connectycube_user_id: "12576473",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 4,
//phone: "230203203",
//service: "Orthopedic",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/10" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/10" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/10')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 9,
//name: "Dr Juan Konare",
//email: "juankonare@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "8:30 AM to 5:30 PM",
//address: "390 Pearl St, New York, NY 10038, USA",
//lat: "40.710664",
//lon: "-74.0000589",
//phoneno: "253625326",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/12.jpg",
//department_id: 7,
//password: "123456",
//created_at: "2023-08-01T05:19:02.000000Z",
//updated_at: "2025-06-19T10:53:33.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "112864506#2",
//connectycube_user_id: "12576472",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 3,
//phone: "253625326",
//service: "Urologist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/9" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/9" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/9')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 7,
//name: "Dr Poll Woker",
//email: "Poll@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "9:00 AM To 9:00 PM",
//address: "455 Water St, New York, NY 10002, USA",
//lat: "40.709912655193264",
//lon: "-73.99545854066162",
//phoneno: "43443566576",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/10.jpg",
//department_id: 2,
//password: "123456",
//created_at: "2023-08-01T05:17:56.000000Z",
//updated_at: "2024-03-13T07:02:16.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "29323518#2",
//connectycube_user_id: "12576471",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 3,
//phone: "43443566576",
//service: "Cardiologist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/7" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/7" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/7')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 6,
//name: "Dr. Leroy Anderson",
//email: "Leroy@gmail.com",
//aboutus: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//working_time: "9:00 AM To 9:00 PM",
//address: "Madison St/St James Pl, New York, NY 10038, USA",
//lat: "40.71186447182015",
//lon: "-73.99940675233154",
//phoneno: "74200120202",
//services: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//healthcare: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/8.jpg",
//department_id: 12,
//password: "123456",
//created_at: "2023-08-01T05:17:11.000000Z",
//updated_at: "2024-03-13T07:02:45.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "1973986917#2",
//connectycube_user_id: "12576470",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 2,
//phone: "74200120202",
//service: "Skin care",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/6" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/6" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/6')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 5,
//name: "Dr. Cate Blanchett",
//email: "Cate@gmail.com",
//aboutus: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//working_time: "9:00 AM to 6:00 PM",
//address: "19/F 222 Broadway, New York, NY 10038, USA",
//lat: "40.71027049252458",
//lon: "-74.00781815980224",
//phoneno: "985232102",
//services: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//healthcare: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/7.jpg",
//department_id: 5,
//password: "123456",
//created_at: "2023-08-01T05:16:45.000000Z",
//updated_at: "2024-03-13T07:03:05.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "984974819#2",
//connectycube_user_id: "12576469",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 2,
//phone: "985232102",
//service: "Eye Care",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/5" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/5" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/5')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 4,
//name: "Dr Giorgos",
//email: "Edward@gmail.com",
//aboutus: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//working_time: "9:00 AM to 6:00 PM",
//address: "1325 Park Ave, New York, NY 10029, USA",
//lat: "40.78934826286402",
//lon: "-73.95060850714115",
//phoneno: "87542695836",
//services: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//healthcare: "Dr. Agnes Ayres is a Maxillofacial Surgeon in New York, NY. Dr. Ayres has more experience with Congenital Cardiac Disorders and Cardiac Care than other specialists in his area. He is affiliated with medical facilities such as Mount Sinai Morningside and Roosevelt Hospital. He is accepting new patients. Be sure to call ahead with Dr. Pinney to book an appointment.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/6.jpg",
//department_id: 7,
//password: "123456",
//created_at: "2023-08-01T05:16:23.000000Z",
//updated_at: "2024-03-13T06:57:45.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "1983197712#2",
//connectycube_user_id: "12576468",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 1,
//phone: "87542695836",
//service: "Urologist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/4" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/4" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/4')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 1,
//name: "Dr. Mahajan",
//email: "mahajan@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "9:00 AM to 6:00 PM",
//address: "96 E Broadway, New York, NY 10002, USA",
//lat: "40.71397887526981",
//lon: "-73.99348443482666",
//phoneno: "+919878767899",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1725962471.jpg",
//department_id: 4,
//password: "123456",
//created_at: "2023-08-01T05:14:47.000000Z",
//updated_at: "2024-09-18T05:08:44.000000Z",
//is_approve: "1",
//consultation_fees: "100",
//login_id: "1415055769#2",
//connectycube_user_id: "12576467",
//connectycube_password: "123456",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 1,
//phone: "+919878767899",
//service: "Ayurveda",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/1" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/1" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/1')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//}
//        {
//id: 23,
//name: "Dr Mark Smith",
//email: "mark_smith12@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "8:00 AM to 6:00 PM",
//address: "445 Pearl St, New York, NY 10005, USA",
//lat: "40.71248253515815",
//lon: "-74.0013808581665",
//phoneno: "8568569862",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252794.jpg",
//department_id: 4,
//password: "123456",
//created_at: "2023-08-01T06:21:01.000000Z",
//updated_at: "2024-03-13T06:58:32.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "8568569862#1",
//connectycube_user_id: "11931615",
//connectycube_password: "Smith@123",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 10,
//phone: "8568569862",
//service: "Ayurveda",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/23" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/23" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/23')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 22,
//name: "Dr Jacson Desauza",
//email: "Jacson@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "8:00 AM to 6:00 PM",
//address: "Q2GM+P57, 10021, New York, New York County, New York",
//lat: "40.77676414606767",
//lon: "-73.966602422297",
//phoneno: "84751425152",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252761.jpg",
//department_id: 10,
//password: "123456",
//created_at: "2023-08-01T05:24:44.000000Z",
//updated_at: "2024-12-05T04:34:19.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "84751425152624297461#2",
//connectycube_user_id: "11716765",
//connectycube_password: "Jacson@123",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 9,
//phone: "84751425152",
//service: "Homeopathic",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/22" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/22" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/22')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 21,
//name: "Dr Anthony gonzalise",
//email: "anthony12@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "8:00 AM to 6:00 PM",
//address: "61 Reade St, New York, NY 10007, USA",
//lat: "40.714857146194994",
//lon: "-74.00661653016357",
//phoneno: "14258569532",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252726.jpg",
//department_id: 9,
//password: "123456",
//created_at: "2023-08-01T05:24:20.000000Z",
//updated_at: "2024-03-13T06:59:17.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "14258569532#1",
//connectycube_user_id: "11931621",
//connectycube_password: "12345678",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 9,
//phone: "14258569532",
//service: "Gastroenterology",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/21" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/21" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/21')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 20,
//name: "Dr Jin Paul",
//email: "jin_paul12@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "8:00 AM to 6:00 PM",
//address: "21 St James Pl, New York, NY 10038, USA",
//lat: "40.711213872634794",
//lon: "-74.00017922852783",
//phoneno: "98562353263",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252707.jpg",
//department_id: 8,
//password: "123456",
//created_at: "2023-08-01T05:23:54.000000Z",
//updated_at: "2024-03-13T06:59:40.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "98562353263885760867#2",
//connectycube_user_id: "11716760",
//connectycube_password: "Paul@123",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 8,
//phone: "98562353263",
//service: "Gynecologist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/20" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/20" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/20')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 19,
//name: "Dr Mark Tescrothic",
//email: "mark_tescrothic@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "9:00 AM to 6:00 PM",
//address: "83 Columbia St, New York, NY 10002, USA",
//lat: "40.71902064329553",
//lon: "-73.98060983155517",
//phoneno: "8523265362",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252383.jpg",
//department_id: 3,
//password: "123456",
//created_at: "2023-08-01T05:23:29.000000Z",
//updated_at: "2024-03-13T06:59:57.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "8523265362#1",
//connectycube_user_id: "11931617",
//connectycube_password: "12345678",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 8,
//phone: "8523265362",
//service: "Dermatologist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/19" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/19" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/19')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 17,
//name: "Dr Michel Jonson",
//email: "michel@gmail.com",
//aboutus: "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Nullam mollis. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapi.",
//working_time: "8:00 AM to 6:00 PM",
//address: "1177B Broadway, New York, NY 10001, USA",
//lat: "40.745069114054516",
//lon: "-73.9889354083374",
//phoneno: "9685236233",
//services: "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Nullam mollis. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapi.",
//healthcare: "Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Nullam mollis. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapi.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252314.jpg",
//department_id: 11,
//password: "123456",
//created_at: "2023-08-01T05:22:36.000000Z",
//updated_at: "2024-03-13T07:00:05.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "9685236233686158200#2",
//connectycube_user_id: "11716752",
//connectycube_password: "Jonson@123",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 7,
//phone: "9685236233",
//service: "Pulmonologist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/17" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/17" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/17')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 16,
//name: "Dr Ethan Noah",
//email: "anthony@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "10:00 AM to 7:00 PM",
//address: "150 Park Row, New York, NY 10007, USA",
//lat: "40.71277530000001",
//lon: "-74.00142377351074",
//phoneno: "8586595659",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252650.jpg",
//department_id: 10,
//password: "123456",
//created_at: "2023-08-01T05:22:09.000000Z",
//updated_at: "2024-03-13T07:00:19.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "85865956591254638871#2",
//connectycube_user_id: "11716744",
//connectycube_password: "Noah@123",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 7,
//phone: "8586595659",
//service: "Homeopathic",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/16" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/16" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/16')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 15,
//name: "Dr James Paul",
//email: "hyori@gmai.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "9:00 AM to 6:00 PM",
//address: "6 Bowery, New York, NY 10013, USA",
//lat: "40.71430416214852",
//lon: "-73.99760430787353",
//phoneno: "3521786546",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252405.jpg",
//department_id: 2,
//password: "123456",
//created_at: "2023-08-01T05:21:45.000000Z",
//updated_at: "2025-06-27T04:03:56.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "3521786546#1",
//connectycube_user_id: "11933985",
//connectycube_password: "Paul@123",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 6,
//phone: "3521786546",
//service: "Cardiologist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/15" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/15" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/15')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 14,
//name: "Dr Charles",
//email: "chrles@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "9:00 AM to 6:00 PM",
//address: "267 Broadway, New York, NY 10007, USA",
//lat: "40.71417404758779",
//lon: "-74.00674527619628",
//phoneno: "3269869415",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/1680252600.jpg",
//department_id: 1,
//password: "123456",
//created_at: "2023-08-01T05:21:15.000000Z",
//updated_at: "2024-03-13T06:57:34.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "32698694151873884053#2",
//connectycube_user_id: "9547786",
//connectycube_password: "Charles@123",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 6,
//phone: "3269869415",
//service: "Dentist",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/14" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/14" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/14')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//},
//{
//id: 13,
//name: "Dr Amily Smith",
//email: "mark_smith@gmail.com",
//aboutus: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//working_time: "8:30 AM to 7:00 PM",
//address: "36 E 10th St, New York, NY 10003, USA",
//lat: "40.71459691898053",
//lon: "-74.0143842074707",
//phoneno: "3202023001",
//services: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//healthcare: "A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.",
//image: "https://demo.freaktemplate.com/bookappointment/public/upload/doctors/16.jpg",
//department_id: 5,
//password: "123456",
//created_at: "2023-08-01T05:20:53.000000Z",
//updated_at: "2023-08-01T05:20:53.000000Z",
//is_approve: "1",
//consultation_fees: "250",
//login_id: "320202300165740232#2",
//connectycube_user_id: "9547785",
//connectycube_password: "Smith@123",
//state: null,
//city: null,
//bank_name: null,
//ifsc_code: null,
//account_no: null,
//account_holder_name: null,
//profile_type: "1",
//city_id: 5,
//phone: "3202023001",
//service: "Eye Care",
//action: "<a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/savedoctor/13" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-edit f-s-25" style="margin-right: 10px;"></i></a><a  rel="tooltip" title="" href="https://demo.freaktemplate.com/bookappointment/backend/doctortiming/13" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-clock f-s-25" style="margin-right: 10px;"></i></a><a onclick="delete_record('https://demo.freaktemplate.com/bookappointment/backend/deletedoctor/13')" rel="tooltip" title="" class="m-b-10 m-l-5" data-original-title="Remove"><i class="fa fa-trash f-s-25"></i></a>"
//}
        $admin = [
            'name' => 'Administrador main',
            'avatar' => 'admin.jpg',
            'especialidad_id' => 1,
            'ciudad_id' => 1,
            'tarifa' => 0,
            'email' => 'admin@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Admin',
        ];
        User::create($admin);
        $doctores = [
            [
                'name' => 'Dr. Mahajan',
                'avatar' => '1725962471.jpg',
                'especialidad_id' => 4,
                'ciudad_id' => 1,
                'tarifa' => 100,
                'email' => 'mahajan@gmail.com',
            ],
            [
                'name' => 'Dr. Giorgos',
                'avatar' => '6.jpg',
                'especialidad_id' => 2,
                'ciudad_id' => 1,
                'tarifa' => 250,
                'email' => 'Edward@gmail.com',
            ],
            [
                'name' => 'Dr. Cate Blanchett',
                'avatar' => '7.jpg',
                'especialidad_id' => 3,
                'ciudad_id' => 1,
                'tarifa' => 250,
                'email' => 'Cate@gmail.com',
            ],
            [
                'name' => 'Dr. Leroy Anderson',
                'avatar' => '8.jpg',
                'especialidad_id' => 4,
                'ciudad_id' => 1,
                'tarifa' => 250,
                'email' => 'Leroy@gmail.com',
            ],
            [
                'name' => 'Dr Poll Woker',
                'avatar' => '10.jpg',
                'especialidad_id' => 5,
                'ciudad_id' => 1,
                'tarifa' => 250,
                'email' => 'Poll@gmail.com',
            ],
            [
                'name' => 'Dr Juan Konare',
                'avatar' => '11.jpg',
                'especialidad_id' => 6,
                'ciudad_id' => 3,
                'tarifa' => 250,
                'email' => 'juankonare@gmail.com',
            ],
            [
                'name' => 'Dr Joseph Martina',
                'avatar' => '17.jpg',
                'especialidad_id' => 9,
                'ciudad_id' => 5,
                'tarifa' => 250,
                'email' => 'martina@gmail.com',
            ],
            [
                'name' => 'Dr Catholina Marin',
                'avatar' => '14.jpg',
                'especialidad_id' => 8,
                'ciudad_id' => 4,
                'tarifa' => 250,
                'email' => 'Catholina@gmail.com',
            ],
            [
                'name' => 'Dr Andrew Simons',
                'avatar' => '15.jpg',
                'especialidad_id' => 6,
                'ciudad_id' => 4,
                'tarifa' => 250,
                'email' => 'Simonse@gmil.com',
            ],
            [
                'name' => 'Dr Jin Paul',
                'avatar' => '1680252707.jpg',
                'especialidad_id' => 8,
                'ciudad_id' => 8,
                'tarifa' => 250,
                'email' => 'jin_paul12@gmail.com',
            ],
            [
                'name' => 'Dr Anthony Gonzalise',
                'avatar' => '1680252726.jpg',
                'especialidad_id' => 9,
                'ciudad_id' => 9,
                'tarifa' => 250,
                'email' => 'anthony12@gmail.com',
            ],
            [
                'name' => 'Dr Jacson Desauza',
                'avatar' => '1680252761.jpg',
                'especialidad_id' => 10,
                'ciudad_id' => 9,
                'tarifa' => 250,
                'email' => 'Jacson@gmail.com',
            ],
            [
                'name' => 'Dr Mark Smith',
                'avatar' => '1680252794.jpg',
                'especialidad_id' => 4,
                'ciudad_id' => 10,
                'tarifa' => 250,
                'email' => 'mark_smith12@gmail.com',
            ],
            [
                'name' => 'Dr Michel Jonson',
                'avatar' => '1680252314.jpg',
                'especialidad_id' => 11,
                'ciudad_id' => 7,
                'tarifa' => 250,
                'email' => 'michel@gmail.com',
            ],
            [
                'name' => 'Dr Ethan Noah',
                'avatar' => '1680252650.jpg',
                'especialidad_id' => 10,
                'ciudad_id' => 7,
                'tarifa' => 250,
                'email' => 'anthony@gmail.com',
            ],
            [
                'name' => 'Dr James Paul',
                'avatar' => '1680252405.jpg',
                'especialidad_id' => 2,
                'ciudad_id' => 6,
                'tarifa' => 250,
                'email' => 'hyori@gmai.com',
            ],
            [
                'name' => 'Dr Charles',
                'avatar' => '1680252600.jpg',
                'especialidad_id' => 1,
                'ciudad_id' => 6,
                'tarifa' => 250,
                'email' => 'chrles@gmail.com',
            ],
            [
                'name' => 'Dr Amily Smith',
                'avatar' => '16.jpg',
                'especialidad_id' => 5,
                'ciudad_id' => 5,
                'tarifa' => 250,
                'email' => 'mark_smith@gmail.com',
            ],
            [
                'name' => 'Dr Mark Tescrothic',
                'avatar' => '1680252383.jpg',
                'especialidad_id' => 3,
                'ciudad_id' => 8,
                'tarifa' => 250,
                'email' => 'mark_tescrothic@gmail.com',
            ],
        ];

        foreach ($doctores as $doc) {
            User::create([
                'name' => $doc['name'],
                'email' => $doc['email'],
                'password' => bcrypt('123456'),
                'especialidad_id' => $doc['especialidad_id'],
                'ciudad_id' => $doc['ciudad_id'],
                'celular' => '87542695836',
                'avatar' => $doc['avatar'],
                'horas_de_trabajo' => '9:00 AM to 6:00 PM',
                'tarifa' => $doc['tarifa'],
                'acerca' => 'A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.',
                'servicio' => 'A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.',
                'cuidado' => 'A doctor diagnoses and treats diseases and conditions, as well as provides treatment in many forms including medication, procedures, surgery, or therapy.',
                'direccion' => '96 E Broadway, New York, NY 10002, USA',
                'lat' => '40.71397887526981',
                'lng' => '-73.99348443482666',
                'role' => 'Doctor',
            ]);
        }

    }
}
